### ISSUE TITLE
Possible bug in get_deriv for adjointsu2 objects

### ISSUE THREAD

**Issue by simone-romiti** [urbach/su2#12]
Please see https://github.com/urbach/su2/blob/4053c09ae54a7a2828c0e3930a2b864e7e132680/adjointfield.hh#L66 

If I understand correctly, adjointsu2 is a class containing 3 numbers (a, b, c) which represent the object as a member of the adjoint representation of su2:
$$ M = a*\sigma_x + b*\sigma_y + c*\sigma_z $$

get_deriv should give back  (as in eq. 5 of [HMC and QCD](https://www.sciencedirect.com/science/article/pii/0550321389903246)
$$ Q = Im(a)*\sigma_x + Im(b)*\sigma_y + Im(c)*\sigma_z $$

so I think the function should be implemented as follows:

``` c++
template<typename Float=double> inline adjointsu2<Float> get_deriv(su2 & A) {
  const Complex a = A.geta(), b = A.getb(), c = A.getc();
  return adjointsu2<Float>(2.*std::imag(b), 2.*std::real(b), 2.*std::imag(c));
}
```

**Comment by urbach** [comment]
> Please see https://github.com/urbach/su2/blob/4053c09ae54a7a2828c0e3930a2b864e7e132680/adjointfield.hh#L66 
> 
> If I understand correctly, adjointsu2 is a class containing 3 numbers (a, b, c) which represent the object as a member of the adjoint representation of su2:
> $$ M = a*\sigma_x + b*\sigma_y + c*\sigma_z $$
> 
> get_deriv should give back  (as in eq. 5 of [HMC and QCD](https://www.sciencedirect.com/science/article/pii/0550321389903246)
> $$ Q = Im(a)*\sigma_x + Im(b)*\sigma_y + Im(c)*\sigma_z $$
> 
> so I think the function should be implemented as follows:
> 
> ``` c++
> template<typename Float=double> inline adjointsu2<Float> get_deriv(su2 & A) {
>   const Complex a = A.geta(), b = A.getb(), c = A.getc();
>   return adjointsu2<Float>(2.*std::imag(b), 2.*std::real(b), 2.*std::imag(c));
> }
> ```

why?

I'm actually pretty sure this piece of code is correct, because I get
acceptance... In the SU(2) case there is not even an element 'c', not
sure what you mean? I parametrise an SU(2) matrix as

( a   b )
(-b*  a*)

**Comment by simone-romiti** [comment]
Ok, understood. You store it as eq. (4.23) of [Gattringer&Lang](https://link.springer.com/book/10.1007/978-3-642-01850-3). Correct?
What is adjointsu2::c used for?

**Comment by urbach** [comment]
> Ok, understood. You store it as eq. (4.23) of [Gattringer&Lang](https://link.springer.com/book/10.1007/978-3-642-01850-3). Correct?
> What is adjointsu2::c used for?

well, but adjointsu2 has three real parameters a, b, c. They multiply
the three Pauli matrices in the exponential representation...
