### ISSUE TITLE
wilson loop evaluated only for 2 spatial distances

### ISSUE THREAD

**Issue by simone-romiti** [urbach/su2#15]
Why do we call this function here?
https://github.com/urbach/su2/blob/919188c275387ff2303f78d31c9fed10f9616c28/measure-u1.cc#L95

```compute_spacial_loops()``` does it for just 2 distances: ```r=2,8```, which are not all and may not be acceptable (e.g. if ```8>Lx```. Please see https://github.com/urbach/su2/pull/11/commits/34f55af6833d17f641a222d6aa51b87926a97cc6

**Comment by urbach** [comment]
> Why do we call this function here?
> https://github.com/urbach/su2/blob/919188c275387ff2303f78d31c9fed10f9616c28/measure-u1.cc#L95
> 
> ```compute_spacial_loops()``` does it for just 2 distances: ```r=2,8```, which are not all and may not be acceptable (e.g. if ```8>Lx```. Please see https://github.com/urbach/su2/pull/11/commits/34f55af6833d17f641a222d6aa51b87926a97cc6

I think I did this for the project for which I wrote this code
originally, and there I needed only a very limited set of
distances. But @christianegross has implemented and is using Wilson
loops, also for the non-planar case.
