### ISSUE TITLE
Function needs more parameters for calculating spatial-spatial plaquette

### ISSUE THREAD

**Issue by christianegross** [urbach/su2#31]
https://github.com/urbach/su2/blob/7cb05b001a04326aea3190d5e534051412b277f4/program-u1.hpp#L166
this should be fixed the same way as in https://github.com/urbach/su2/pull/30#issue-1364518498.

**Comment by simone-romiti** [comment]
Done. Please see https://github.com/urbach/su2/commit/b9b74d1acc809460ca2ba0d00bbc6bb49cfbc68d
